"""empty message

Revision ID: 00187f1862a1
Revises: 3bdf8fc85715
Create Date: 2020-01-23 06:56:40.746990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00187f1862a1'
down_revision = '3bdf8fc85715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('title', sa.String(length=64), nullable=True))
    op.add_column('articles', sa.Column('title_slug', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_articles_title'), 'articles', ['title'], unique=False)
    op.create_index(op.f('ix_articles_title_slug'), 'articles', ['title_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_title_slug'), table_name='articles')
    op.drop_index(op.f('ix_articles_title'), table_name='articles')
    op.drop_column('articles', 'title_slug')
    op.drop_column('articles', 'title')
    # ### end Alembic commands ###
