"""empty message

Revision ID: 06bca08b96f1
Revises: 00187f1862a1
Create Date: 2020-01-24 02:20:25.785116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06bca08b96f1'
down_revision = '00187f1862a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('draft_title', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'draft_title')
    # ### end Alembic commands ###
