"""request to publish added

Revision ID: 2cd1390f0a84
Revises: e4ac19017324
Create Date: 2020-02-02 06:29:03.252849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cd1390f0a84'
down_revision = 'e4ac19017324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_to_publish', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_articles_request_to_publish'), ['request_to_publish'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_request_to_publish'))
        batch_op.drop_column('request_to_publish')

    # ### end Alembic commands ###
