"""Initial migration.

Revision ID: 2de1d2afe5b7
Revises: 
Create Date: 2020-05-23 06:43:55.663174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de1d2afe5b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_type_name'), ['name'], unique=False)

    op.create_table('creative_works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('date_published', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creative_works', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creative_works_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_creative_works_tmdb_id'), ['tmdb_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_creative_works_type'), ['type'], unique=False)

    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_tmdb_id'), ['tmdb_id'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_default'), ['default'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_tags_tmdb_id'), ['tmdb_id'], unique=True)

    op.create_table('directs',
    sa.Column('directed_id', sa.Integer(), nullable=True),
    sa.Column('director_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['directed_id'], ['creative_works.id'], ),
    sa.ForeignKeyConstraint(['director_id'], ['people.id'], )
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('avatar_hash', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_type_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('title_slug', sa.String(length=64), nullable=True),
    sa.Column('draft_title', sa.String(length=64), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('draft', sa.Text(), nullable=True),
    sa.Column('blurb', sa.String(length=256), nullable=True),
    sa.Column('youtube', sa.String(length=64), nullable=True),
    sa.Column('final_verdict', sa.String(length=256), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('letter_rating', sa.String(length=3), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_edit', sa.DateTime(), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('request_to_publish', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['article_type_id'], ['article_type.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['creative_works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_created'), ['created'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_last_edit'), ['last_edit'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_publish_date'), ['publish_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_rating'), ['rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_request_to_publish'), ['request_to_publish'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_title_slug'), ['title_slug'], unique=False)

    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_table('article_tags',
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_tags')
    op.drop_table('follows')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_title_slug'))
        batch_op.drop_index(batch_op.f('ix_articles_title'))
        batch_op.drop_index(batch_op.f('ix_articles_request_to_publish'))
        batch_op.drop_index(batch_op.f('ix_articles_rating'))
        batch_op.drop_index(batch_op.f('ix_articles_publish_date'))
        batch_op.drop_index(batch_op.f('ix_articles_last_edit'))
        batch_op.drop_index(batch_op.f('ix_articles_is_published'))
        batch_op.drop_index(batch_op.f('ix_articles_created'))

    op.drop_table('articles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('directs')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_tmdb_id'))
        batch_op.drop_index(batch_op.f('ix_tags_name'))
        batch_op.drop_index(batch_op.f('ix_tags_id'))

    op.drop_table('tags')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_default'))

    op.drop_table('roles')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_tmdb_id'))
        batch_op.drop_index(batch_op.f('ix_people_name'))

    op.drop_table('people')
    with op.batch_alter_table('creative_works', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_works_type'))
        batch_op.drop_index(batch_op.f('ix_creative_works_tmdb_id'))
        batch_op.drop_index(batch_op.f('ix_creative_works_name'))

    op.drop_table('creative_works')
    with op.batch_alter_table('article_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_type_name'))

    op.drop_table('article_type')
    # ### end Alembic commands ###
