"""Simplified director_relationship

Revision ID: 364b0c25e45c
Revises: 7c567e09ff36
Create Date: 2020-05-22 21:55:55.839034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364b0c25e45c'
down_revision = '7c567e09ff36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_tags', schema=None) as batch_op:
        batch_op.alter_column('article_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('tag_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('directs', schema=None) as batch_op:
        batch_op.alter_column('directed_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('director_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('directs', schema=None) as batch_op:
        batch_op.alter_column('director_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('directed_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('article_tags', schema=None) as batch_op:
        batch_op.alter_column('tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('article_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
