"""Added letter grade to articles.

Revision ID: 56395ef8f9cb
Revises: edef2a780ab8
Create Date: 2020-04-21 09:44:25.297708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56395ef8f9cb'
down_revision = 'edef2a780ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('letter_rating', sa.String(length=3), nullable=True))
        batch_op.create_index(batch_op.f('ix_articles_created'), ['created'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_last_edit'), ['last_edit'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_rating'), ['rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_request_to_publish'), ['request_to_publish'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_title_slug'), ['title_slug'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_title_slug'))
        batch_op.drop_index(batch_op.f('ix_articles_title'))
        batch_op.drop_index(batch_op.f('ix_articles_request_to_publish'))
        batch_op.drop_index(batch_op.f('ix_articles_rating'))
        batch_op.drop_index(batch_op.f('ix_articles_last_edit'))
        batch_op.drop_index(batch_op.f('ix_articles_is_published'))
        batch_op.drop_index(batch_op.f('ix_articles_created'))
        batch_op.drop_column('letter_rating')

    # ### end Alembic commands ###
