"""reduced complexity of tag relationship

Revision ID: 7c567e09ff36
Revises: 56395ef8f9cb
Create Date: 2020-04-29 01:23:07.999140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c567e09ff36'
down_revision = '56395ef8f9cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_tags', schema=None) as batch_op:
        batch_op.alter_column('article_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('tag_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_tags', schema=None) as batch_op:
        batch_op.alter_column('tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('article_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
