"""added articles

Revision ID: c8defd45da1c
Revises: f79d82990411
Create Date: 2020-01-17 06:52:26.327145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8defd45da1c'
down_revision = 'f79d82990411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('draft', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_edit', sa.DateTime(), nullable=True),
    sa.Column('published', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_created'), 'articles', ['created'], unique=False)
    op.create_index(op.f('ix_articles_last_edit'), 'articles', ['last_edit'], unique=False)
    op.create_index(op.f('ix_articles_published'), 'articles', ['published'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_published'), table_name='articles')
    op.drop_index(op.f('ix_articles_last_edit'), table_name='articles')
    op.drop_index(op.f('ix_articles_created'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
