"""empty message

Revision ID: c9be9d7ebb3e
Revises: bfc99b28fa27
Create Date: 2020-03-04 06:40:40.525892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9be9d7ebb3e'
down_revision = 'bfc99b28fa27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tmdb_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tags_tmdb_id'), ['tmdb_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_tmdb_id'))
        batch_op.drop_column('tmdb_id')

    # ### end Alembic commands ###
