"""Added same_as to creative work.

Revision ID: e95115b16c55
Revises: 2de1d2afe5b7
Create Date: 2020-05-23 12:05:51.683426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95115b16c55'
down_revision = '2de1d2afe5b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_works', schema=None) as batch_op:
        batch_op.add_column(sa.Column('same_as', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint('same_as', ['same_as'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_works', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('same_as')

    # ### end Alembic commands ###
