"""Created new column to replace published.

Revision ID: edef2a780ab8
Revises: c9be9d7ebb3e
Create Date: 2020-03-15 17:33:15.555163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edef2a780ab8'
down_revision = 'c9be9d7ebb3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index('ix_articles_published')
        batch_op.alter_column(column_name='published',new_column_name="publish_date")
        batch_op.create_index(batch_op.f('ix_articles_publish_date'), ['publish_date'], unique=False)

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index('ix_tags_tmdb_id')
        batch_op.create_index(batch_op.f('ix_tags_tmdb_id'), ['tmdb_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_tmdb_id'))
        batch_op.create_index('ix_tags_tmdb_id', ['tmdb_id'], unique=False)

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index('ix_articles_publish_date')
        batch_op.alter_column(column_name='publish_date', nullable=True,new_column_name="published")
        batch_op.create_index(batch_op.f('ix_articles_published'), ['published'], unique=False)

    # ### end Alembic commands ###
